import Product from '../models/Product.js';
import StockMovement from '../models/StockMovement.js';
import {imagekit,imageKitReady} from '../config/imagekit.js';
export async function list(req,res){res.json(await Product.find({shopId:req.user.shopId}).sort({createdAt:-1}))}
export async function getOne(req,res){const p=await Product.findOne({_id:req.params.id,shopId:req.user.shopId});if(!p)return res.status(404).json({message:'Product not found'});res.json(p)}
async function uploadIfPresent(file){if(!file)return null;if(!imageKitReady())throw new Error('ImageKit is not configured');const result=await imagekit.upload({file:file.buffer,fileName:`product-${Date.now()}-${file.originalname.replace(/[^a-zA-Z0-9._-]/g,'_')}`,folder:'/shoppilot/products'});return {url:result.url,fileId:result.fileId,name:result.name}}
export async function create(req,res){try{const image=await uploadIfPresent(req.file);const body={...req.body,stock:Number(req.body.stock||0),purchasePrice:Number(req.body.purchasePrice||0),sellingPrice:Number(req.body.sellingPrice||0),lowStockLimit:Number(req.body.lowStockLimit||0),shopId:req.user.shopId};if(image)body.image=image;const p=await Product.create(body);if(p.stock>0)await StockMovement.create({shopId:req.user.shopId,productId:p._id,type:'OPENING',quantity:p.stock,previousStock:0,newStock:p.stock,note:'Opening stock'});res.status(201).json(p)}catch(e){res.status(400).json({message:e.code===11000?'SKU already exists':e.message})}}
export async function update(req,res){try{const old=await Product.findOne({_id:req.params.id,shopId:req.user.shopId});if(!old)return res.status(404).json({message:'Product not found'});const image=await uploadIfPresent(req.file);const body={...req.body};['stock','purchasePrice','sellingPrice','lowStockLimit'].forEach(k=>{if(body[k]!==undefined)body[k]=Number(body[k])});if(image)body.image=image;const updated=await Product.findOneAndUpdate({_id:old._id,shopId:req.user.shopId},body,{new:true,runValidators:true});if(body.stock!==undefined&&body.stock!==old.stock)await StockMovement.create({shopId:req.user.shopId,productId:old._id,type:'ADJUSTMENT',quantity:body.stock-old.stock,previousStock:old.stock,newStock:body.stock,note:'Manual stock adjustment'});res.json(updated)}catch(e){res.status(400).json({message:e.message})}}
export async function remove(req,res){await Product.deleteOne({_id:req.params.id,shopId:req.user.shopId});res.json({message:'Product deleted'})}
export async function history(req,res){res.json(await StockMovement.find({shopId:req.user.shopId,productId:req.params.id}).sort({createdAt:-1}).limit(300))}
